# Generated by Django 6.0 on 2025-12-08 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pipoca',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sabor', models.CharField(max_length=200)),
                ('preco', models.FloatField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='pipoca/')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categoria', to='pipoca.categoria')),
            ],
        ),
    ]
